title: Nithya Balasundar
#logo: /assets/img/headshot_circle.png
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

