title: Nithya Balasundar
#logo: 33980043.jpeg
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

